### PR TITLE
Add state validation for gameSetup, gameEnd and state machine completeness

### PR DESCRIPTION
**Pull request by jaredpearson**
Instead of working on my game's logic (aka procrastination), I spent some time updating the state validation to add new validations. Existing validation of checking that all transitions point to a valid ID is kept intact.

* States `gameSetup` and `gameEnd` should exist and should match the documentation
* The defined transitions should start at `gameSetup` and end up at `gameEnd` at some point.

### CODE REVIEW

**Comment by danielholmes** [comment]
This is very nice! Thanks @jaredpearson

**Comment by danielholmes** [comment]
Tests are failing once I merged it in. I'll make a new release when i find some time to get the tests working.

**Comment by jaredpearson** [comment]
@danielholmes - Figured out the issue with the build failing - it's because the changes I added used features from PHP 7.1+ even though the build runs against >= 7.0. I've updated the build file in PR #31. Let me know what you think!

**Comment by danielholmes** [comment]
Released in [0.2.0](https://packagist.org/packages/dholmes/bga-workbench#0.2.0)

**Pull request merged**
